"""
rockusb_winusb.py - Rockchip rockusb client using direct Win32 WinUSB API.

Sidesteps libusb-on-Windows compositey-ness: we have WinUSB bound to MI_01
of the recovery composite device via Zadig, and we just open it directly
through SetupAPI + WinUSB.

The MI_01 interface's DeviceInterfaceGUID is randomly generated by Zadig
(passed in via command line - default is the GUID Zadig set on this host).
Endpoint addresses are hardcoded to what `rockusb.py probe` showed:
  OUT bulk: 0x04
  IN  bulk: 0x83

CLI:
    python rockusb_winusb.py probe
    python rockusb_winusb.py info
    python rockusb_winusb.py read-lba <start> <count> <out.bin>
    python rockusb_winusb.py reset
"""

import sys
import struct
import ctypes
import ctypes.wintypes as wt
from ctypes import (
    POINTER, byref, sizeof, Structure, c_void_p, c_ulong, c_byte, c_ubyte,
    c_ushort, c_uint, c_wchar_p, c_int,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
# Zadig-assigned DeviceInterfaceGUID for MI_01 on this host. The script will
# also accept --guid on the command line if it ever changes.
DEFAULT_GUID = '{69800760-AD24-4938-B341-49FEFE9C9C7C}'

EP_OUT = 0x04
EP_IN  = 0x83

DIGCF_PRESENT          = 0x02
DIGCF_DEVICEINTERFACE  = 0x10
GENERIC_READ           = 0x80000000
GENERIC_WRITE          = 0x40000000
FILE_SHARE_READ        = 1
FILE_SHARE_WRITE       = 2
OPEN_EXISTING          = 3
FILE_FLAG_OVERLAPPED   = 0x40000000
ERROR_NO_MORE_ITEMS    = 259
ERROR_INSUFFICIENT_BUFFER = 122
INVALID_HANDLE_VALUE   = c_void_p(-1).value

# Rockchip CBW opcodes
CMD_TEST_UNIT_READY  = 0x00
CMD_READ_FLASH_ID    = 0x01
CMD_READ_LBA         = 0x14
CMD_WRITE_LBA        = 0x15
CMD_READ_FLASH_INFO  = 0x1A
CMD_READ_CHIP_INFO   = 0x1B
CMD_READ_CAPABILITY  = 0x1D
CMD_DEVICE_RESET     = 0xFF

CBW_SIGNATURE = 0x43425355
CSW_SIGNATURE = 0x53425355

# ---------------------------------------------------------------------------
# Win32 ctypes
# ---------------------------------------------------------------------------
setupapi = ctypes.windll.setupapi
kernel32 = ctypes.windll.kernel32
winusb   = ctypes.windll.winusb

class GUID(Structure):
    _fields_ = [
        ('Data1', c_ulong),
        ('Data2', c_ushort),
        ('Data3', c_ushort),
        ('Data4', c_byte * 8),
    ]

def parse_guid(s):
    s = s.strip().strip('{}').lower()
    parts = s.split('-')
    g = GUID()
    g.Data1 = int(parts[0], 16)
    g.Data2 = int(parts[1], 16)
    g.Data3 = int(parts[2], 16)
    d4 = bytes.fromhex(parts[3]) + bytes.fromhex(parts[4])
    for i, b in enumerate(d4):
        g.Data4[i] = b
    return g

class SP_DEVICE_INTERFACE_DATA(Structure):
    _fields_ = [
        ('cbSize', c_ulong),
        ('InterfaceClassGuid', GUID),
        ('Flags', c_ulong),
        ('Reserved', c_void_p),
    ]

# SP_DEVICE_INTERFACE_DETAIL_DATA_W has variable-length DevicePath. Use a
# generous fixed buffer.
class SP_DEVICE_INTERFACE_DETAIL_DATA_W(Structure):
    _fields_ = [
        ('cbSize', c_ulong),
        ('DevicePath', wt.WCHAR * 1024),
    ]

# Function signatures
setupapi.SetupDiGetClassDevsW.argtypes = [POINTER(GUID), c_wchar_p, c_void_p, c_ulong]
setupapi.SetupDiGetClassDevsW.restype = c_void_p

setupapi.SetupDiEnumDeviceInterfaces.argtypes = [
    c_void_p, c_void_p, POINTER(GUID), c_ulong, POINTER(SP_DEVICE_INTERFACE_DATA)
]
setupapi.SetupDiEnumDeviceInterfaces.restype = wt.BOOL

setupapi.SetupDiGetDeviceInterfaceDetailW.argtypes = [
    c_void_p, POINTER(SP_DEVICE_INTERFACE_DATA), POINTER(SP_DEVICE_INTERFACE_DETAIL_DATA_W),
    c_ulong, POINTER(c_ulong), c_void_p,
]
setupapi.SetupDiGetDeviceInterfaceDetailW.restype = wt.BOOL

setupapi.SetupDiDestroyDeviceInfoList.argtypes = [c_void_p]
setupapi.SetupDiDestroyDeviceInfoList.restype = wt.BOOL

kernel32.CreateFileW.argtypes = [c_wchar_p, c_ulong, c_ulong, c_void_p, c_ulong, c_ulong, c_void_p]
kernel32.CreateFileW.restype = c_void_p

kernel32.CloseHandle.argtypes = [c_void_p]
kernel32.CloseHandle.restype = wt.BOOL

winusb.WinUsb_Initialize.argtypes = [c_void_p, POINTER(c_void_p)]
winusb.WinUsb_Initialize.restype = wt.BOOL

winusb.WinUsb_Free.argtypes = [c_void_p]
winusb.WinUsb_Free.restype = wt.BOOL

winusb.WinUsb_WritePipe.argtypes = [c_void_p, c_ubyte, c_void_p, c_ulong, POINTER(c_ulong), c_void_p]
winusb.WinUsb_WritePipe.restype = wt.BOOL

winusb.WinUsb_ReadPipe.argtypes = [c_void_p, c_ubyte, c_void_p, c_ulong, POINTER(c_ulong), c_void_p]
winusb.WinUsb_ReadPipe.restype = wt.BOOL

winusb.WinUsb_SetPipePolicy.argtypes = [c_void_p, c_ubyte, c_ulong, c_ulong, c_void_p]
winusb.WinUsb_SetPipePolicy.restype = wt.BOOL

winusb.WinUsb_ResetPipe.argtypes = [c_void_p, c_ubyte]
winusb.WinUsb_ResetPipe.restype = wt.BOOL

winusb.WinUsb_ControlTransfer.argtypes = [
    c_void_p,
    ctypes.c_uint64,  # WINUSB_SETUP_PACKET as 8-byte struct
    c_void_p, c_ulong, POINTER(c_ulong), c_void_p,
]
winusb.WinUsb_ControlTransfer.restype = wt.BOOL

# Pipe policy IDs
PIPE_TRANSFER_TIMEOUT = 0x03
RAW_IO                = 0x07
RESET_PIPE_ON_RESUME  = 0x09

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _last_err(prefix):
    e = ctypes.GetLastError()
    return OSError(f'{prefix} failed: GetLastError={e}')


def list_device_paths(guid_str):
    """Yield all device paths registered under the given DeviceInterfaceGUID."""
    guid = parse_guid(guid_str)
    h = setupapi.SetupDiGetClassDevsW(byref(guid), None, None, DIGCF_PRESENT | DIGCF_DEVICEINTERFACE)
    if h == INVALID_HANDLE_VALUE:
        raise _last_err('SetupDiGetClassDevs')
    try:
        idx = 0
        while True:
            iface = SP_DEVICE_INTERFACE_DATA()
            iface.cbSize = sizeof(SP_DEVICE_INTERFACE_DATA)
            if not setupapi.SetupDiEnumDeviceInterfaces(h, None, byref(guid), idx, byref(iface)):
                err = ctypes.GetLastError()
                if err == ERROR_NO_MORE_ITEMS:
                    break
                raise OSError(f'SetupDiEnumDeviceInterfaces[{idx}] failed: {err}')

            detail = SP_DEVICE_INTERFACE_DETAIL_DATA_W()
            # On 64-bit Windows, the documented cbSize of this struct is 8.
            # On 32-bit, it's 6. The struct is variable-length but we set
            # cbSize to the fixed-header size, NOT sizeof(detail).
            detail.cbSize = 8 if sizeof(c_void_p) == 8 else 6
            req = c_ulong()
            ok = setupapi.SetupDiGetDeviceInterfaceDetailW(
                h, byref(iface), byref(detail), sizeof(detail), byref(req), None
            )
            if not ok:
                raise _last_err('SetupDiGetDeviceInterfaceDetail')
            yield detail.DevicePath
            idx += 1
    finally:
        setupapi.SetupDiDestroyDeviceInfoList(h)


class WinUsbDevice:
    def __init__(self, device_path, pipe_timeout_ms=4000):
        self.device_path = device_path
        self.h = kernel32.CreateFileW(
            device_path,
            GENERIC_READ | GENERIC_WRITE,
            FILE_SHARE_READ | FILE_SHARE_WRITE,
            None,
            OPEN_EXISTING,
            FILE_FLAG_OVERLAPPED,
            None,
        )
        if self.h == INVALID_HANDLE_VALUE:
            raise _last_err('CreateFile')
        self.winusb = c_void_p()
        if not winusb.WinUsb_Initialize(self.h, byref(self.winusb)):
            kernel32.CloseHandle(self.h)
            raise _last_err('WinUsb_Initialize')
        # Set per-pipe timeout so reads don't hang forever if the device
        # never responds. WinUSB default is "wait forever".
        timeout = c_ulong(pipe_timeout_ms)
        for ep in (EP_OUT, EP_IN):
            if not winusb.WinUsb_SetPipePolicy(self.winusb, ep,
                                                PIPE_TRANSFER_TIMEOUT,
                                                sizeof(timeout), byref(timeout)):
                # not fatal - just print a warning
                err = ctypes.GetLastError()
                print(f'  (SetPipePolicy(ep=0x{ep:02x}, TIMEOUT={pipe_timeout_ms}ms) failed: {err})')

    def reset_pipes(self):
        for ep in (EP_OUT, EP_IN):
            winusb.WinUsb_ResetPipe(self.winusb, ep)

    def msc_bulk_reset(self, interface_num=1):
        """Issue USB Mass Storage Class Bulk-Only Reset on the control pipe.
        bmRequestType=0x21, bRequest=0xFF, wValue=0, wIndex=interface, wLength=0."""
        # WINUSB_SETUP_PACKET as packed uint64 (LE):
        #   byte 0: RequestType
        #   byte 1: Request
        #   bytes 2..3: Value (LE)
        #   bytes 4..5: Index (LE)
        #   bytes 6..7: Length (LE)
        setup = struct.pack('<BBHHH', 0x21, 0xFF, 0, interface_num, 0)
        setup_int = struct.unpack('<Q', setup)[0]
        transferred = c_ulong()
        ok = winusb.WinUsb_ControlTransfer(self.winusb, setup_int, None, 0, byref(transferred), None)
        if not ok:
            err = ctypes.GetLastError()
            print(f'  (msc_bulk_reset control transfer failed: {err})')
            return False
        return True

    def close(self):
        if self.winusb:
            winusb.WinUsb_Free(self.winusb)
            self.winusb = c_void_p()
        if self.h:
            kernel32.CloseHandle(self.h)
            self.h = None

    def write_pipe(self, ep, data):
        transferred = c_ulong()
        buf = (c_ubyte * len(data)).from_buffer_copy(data)
        if not winusb.WinUsb_WritePipe(self.winusb, ep, buf, len(data), byref(transferred), None):
            raise _last_err(f'WinUsb_WritePipe(ep=0x{ep:02x}, len={len(data)})')
        return transferred.value

    def read_pipe(self, ep, length):
        transferred = c_ulong()
        buf = (c_ubyte * length)()
        if not winusb.WinUsb_ReadPipe(self.winusb, ep, buf, length, byref(transferred), None):
            raise _last_err(f'WinUsb_ReadPipe(ep=0x{ep:02x}, len={length})')
        return bytes(buf[:transferred.value])


# ---------------------------------------------------------------------------
# Rockusb protocol
# ---------------------------------------------------------------------------
class Rockusb:
    def __init__(self, dev: WinUsbDevice):
        self.dev = dev
        self._tag = 1

    def _next_tag(self):
        t = self._tag
        self._tag = (self._tag + 1) & 0xffffffff
        return t

    def cmd(self, opcode, data_xfer_len=0, data_in=True, params_be=b''):
        tag = self._next_tag()
        flags = 0x80 if data_in else 0x00
        cbwcb = bytes([opcode]) + params_be
        if len(cbwcb) > 16:
            raise RuntimeError(f'CBWCB too long: {len(cbwcb)}')
        cmd_len = len(cbwcb)
        cbwcb = cbwcb.ljust(16, b'\x00')

        cbw = struct.pack('<IIIBBB', CBW_SIGNATURE, tag, data_xfer_len, flags, 0, cmd_len) + cbwcb
        assert len(cbw) == 31

        self.dev.write_pipe(EP_OUT, cbw)

        data = b''
        if data_xfer_len > 0:
            if data_in:
                data = self.dev.read_pipe(EP_IN, data_xfer_len)
            else:
                # OUT data phase not implemented in cmd(); use directly
                raise NotImplementedError

        csw = self.dev.read_pipe(EP_IN, 13)
        if len(csw) != 13:
            raise RuntimeError(f'CSW size wrong: {len(csw)}')
        sig, rsp_tag, residue, status = struct.unpack('<IIIB', csw)
        if sig != CSW_SIGNATURE:
            raise RuntimeError(f'CSW signature wrong: 0x{sig:08x}')
        if rsp_tag != tag:
            raise RuntimeError(f'CSW tag mismatch: got {rsp_tag} expected {tag}')
        return status, residue, data


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def hex_dump(data, prefix='  '):
    if not data:
        return ''
    out = []
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hx = ' '.join(f'{b:02x}' for b in chunk)
        ascii_repr = ''.join(chr(b) if 32 <= b < 127 else '.' for b in chunk)
        out.append(f'{prefix}{i:04x}  {hx:<47s}  {ascii_repr}')
    return '\n'.join(out)


def open_first(guid_str):
    paths = list(list_device_paths(guid_str))
    if not paths:
        raise RuntimeError(f'No device with DeviceInterfaceGUID {guid_str} found.')
    if len(paths) > 1:
        print(f'Multiple devices with that GUID, using first:')
        for p in paths: print(f'  {p}')
    return WinUsbDevice(paths[0])


def cmd_probe(guid):
    paths = list(list_device_paths(guid))
    print(f'DeviceInterfaceGUID {guid}:')
    if not paths:
        print('  (no devices)')
        return
    for p in paths:
        print(f'  path: {p}')
    # Try opening
    dev = WinUsbDevice(paths[0])
    print(f'Opened OK: handle={dev.h} winusb_handle={dev.winusb}')
    dev.close()


def cmd_info(guid):
    dev = open_first(guid)
    # Some rockusb gadgets need a Mass-Storage Bulk Reset before the first CBW.
    print('Sending USB MSC Bulk Reset...')
    dev.msc_bulk_reset(interface_num=1)
    dev.reset_pipes()
    rk = Rockusb(dev)
    try:
        print('TestUnitReady...')
        s, _, _ = rk.cmd(CMD_TEST_UNIT_READY, 0)
        print(f'TestUnitReady: status={s}')

        s, _, d = rk.cmd(CMD_READ_CAPABILITY, 8)
        print(f'ReadCapability: status={s}')
        print(hex_dump(d))

        s, _, d = rk.cmd(CMD_READ_FLASH_ID, 5)
        print(f'ReadFlashID: status={s}')
        print(hex_dump(d))

        s, _, d = rk.cmd(CMD_READ_FLASH_INFO, 11)
        print(f'ReadFlashInfo: status={s}')
        print(hex_dump(d))
        if d and len(d) >= 4:
            sectors = struct.unpack('<I', d[:4])[0]
            print(f'  -> flash size: {sectors} sectors = {sectors * 512 / (1<<30):.2f} GiB')

        s, _, d = rk.cmd(CMD_READ_CHIP_INFO, 16)
        print(f'ReadChipInfo: status={s}')
        print(hex_dump(d))
        # ASCII chip name?
        ascii_name = ''.join(chr(b) for b in d if 32 <= b < 127).strip()
        if ascii_name:
            print(f'  -> ASCII tag: {ascii_name!r}')
    finally:
        dev.close()


def cmd_read_lba(guid, args):
    if len(args) != 3:
        print('Usage: read-lba <start_sector> <count> <out.bin>')
        sys.exit(1)
    start = int(args[0], 0); count = int(args[1], 0); out = args[2]
    dev = open_first(guid)
    rk = Rockusb(dev)
    try:
        params = struct.pack('>IH', start, count) + b'\x00\x00'
        s, _, d = rk.cmd(CMD_READ_LBA, count * 512, data_in=True, params_be=params)
        print(f'ReadLBA(start={start}, count={count}): status={s}, got {len(d)} bytes')
        if d:
            with open(out, 'wb') as f:
                f.write(d)
            print(f'Wrote {len(d)} bytes to {out}')
    finally:
        dev.close()


def main():
    args = sys.argv[1:]
    guid = DEFAULT_GUID
    if args and args[0] == '--guid':
        guid = args[1]; args = args[2:]
    if not args:
        print(__doc__); sys.exit(1)
    cmd, *rest = args
    if cmd == 'probe':       cmd_probe(guid)
    elif cmd == 'info':      cmd_info(guid)
    elif cmd == 'read-lba':  cmd_read_lba(guid, rest)
    elif cmd == 'reset':
        dev = open_first(guid)
        Rockusb(dev).cmd(CMD_DEVICE_RESET, 0)
        dev.close()
        print('Reset sent')
    else:
        print(f'Unknown command: {cmd}'); sys.exit(1)

if __name__ == '__main__':
    main()
